### ISSUE TITLE
Complete school journey

### ISSUE THREAD

**Issue by sophielevens** [fac-12/homesafe#5]
As a school representative, I want to be able to login and access a list of any changes to the pick up schedule on a daily basis

This will include: 
- [x] #13  Login form 
- [x] #16 Register form 
- [x] #12  Email validation for the school upon registration
- [x] #15 See daily schedule of pick ups
- [x] #14 Create form to search and filter pick ups with date input 
- [ ] #17 An option to print the schedule

**Comment by Gbaja** [comment]
We decided we won't have the print schedule feature in this build.

**Comment by Dragomirc** [comment]
The issue #17 is a stretch goal
