### ISSUE TITLE
Complete parent journey

### ISSUE THREAD

**Issue by sophielevens** [fac-12/homesafe#7]
As a parent, I want to be able to register, login and schedule pick ups within the app so that I can arrange a safe pick up for my child.
This will include the following features: 

- [x] #4  Parent Register form 
- [x] #11 Parent Login form 
- [x] #10 Schedule a pick up 
- [x] #9 Add a child 
- [x] #8 Add a Designated Adult
- [x] See all scheduled pickups
